# Generated by Django 5.2 on 2025-04-15 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('row_type', models.CharField(max_length=50)),
                ('credit_sem1', models.FloatField(default=0)),
                ('credit_sem2', models.FloatField(default=0)),
                ('credit_sem3', models.FloatField(default=0)),
                ('credit_sem4', models.FloatField(default=0)),
                ('credit_sem5', models.FloatField(default=0)),
                ('credit_sem6', models.FloatField(default=0)),
                ('credit_sem7', models.FloatField(default=0)),
                ('credit_sem8', models.FloatField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('credit', models.FloatField()),
                ('plo', models.CharField(blank=True, max_length=50)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.creditrow')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.curriculum')),
            ],
        ),
    ]
