# Generated by Django 5.2 on 2025-04-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='row',
            new_name='credit_row',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem1',
            new_name='credits_sem1',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem2',
            new_name='credits_sem2',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem3',
            new_name='credits_sem3',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem4',
            new_name='credits_sem4',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem5',
            new_name='credits_sem5',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem6',
            new_name='credits_sem6',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem7',
            new_name='credits_sem7',
        ),
        migrations.RenameField(
            model_name='creditrow',
            old_name='credit_sem8',
            new_name='credits_sem8',
        ),
    ]
