# Generated by Django 5.2 on 2025-04-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_rename_row_course_credit_row_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='xxx-000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='table.creditrow'),
        ),
        migrations.AlterField(
            model_name='course',
            name='plo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ปีที่ 1/1'), (2, 'ปีที่ 1/2'), (3, 'ปีที่ 2/1'), (4, 'ปีที่ 2/2'), (5, 'ปีที่ 3/1'), (6, 'ปีที่ 3/2'), (7, 'ปีที่ 4/1'), (8, 'ปีที่ 4/2')]),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='credits_sem8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='row_type',
            field=models.CharField(choices=[('general', 'General Education'), ('core', 'Core Education'), ('free', 'Free Elective'), ('plo', 'PLO Based')], max_length=10),
        ),
    ]
