# Generated by Django 5.2 on 2025-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_rename_name_course_course_name_remove_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='year',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
