# Generated by Django 5.2 on 2025-04-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_remove_curriculum_year_curriculum_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='YLOPerPLOSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plo', models.CharField(max_length=50)),
                ('semester', models.PositiveSmallIntegerField()),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.curriculum')),
            ],
        ),
    ]
