# Generated by Django 5.2 on 2025-05-01 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_yloperplosemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSECItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('K', 'Knowledge'), ('S', 'Skills'), ('E', 'Ethics'), ('C', 'Character')], max_length=1)),
                ('description', models.TextField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.curriculum')),
            ],
        ),
    ]
