# Generated by Django 5.2 on 2025-05-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_ksecitem_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='character',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ethics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='knowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
