# Generated by Django 5.2 on 2025-05-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_course_character_course_ethics_course_knowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksecitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ksecitem',
            name='category_type',
            field=models.CharField(choices=[('GE', 'General Education'), ('CE', 'Core Education')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ksecitem',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ksecitem',
            name='type',
            field=models.CharField(choices=[('K', 'Knowledge'), ('S', 'Skill'), ('E', 'Ethics'), ('C', 'Character')], max_length=1),
        ),
    ]
