# Generated by Django 5.2 on 2025-05-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_ksecitem_sort_order_alter_ksecitem_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('clo', models.TextField()),
                ('bloom', models.CharField(blank=True, max_length=50, null=True)),
                ('k', models.CharField(blank=True, max_length=20, null=True)),
                ('s', models.CharField(blank=True, max_length=20, null=True)),
                ('e', models.CharField(blank=True, max_length=20, null=True)),
                ('c', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.course')),
            ],
            options={
                'db_table': 'table_clo',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CLOSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_score', models.IntegerField(default=0)),
                ('k_percent', models.FloatField(default=0.0)),
                ('s_percent', models.FloatField(default=0.0)),
                ('e_percent', models.FloatField(default=0.0)),
                ('c_percent', models.FloatField(default=0.0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='table.course')),
            ],
            options={
                'db_table': 'table_clo_summary',
            },
        ),
    ]
