# Generated by Django 5.2 on 2025-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_clo_closummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='clo_edit_password',
            field=models.CharField(blank=True, help_text='รหัสผ่านสำหรับปลดล็อกหน้า CLO-KSEC Mapping', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='password',
            field=models.CharField(blank=True, help_text='รหัสผ่านสำหรับปลดล็อกโหมดแก้ไขของตารางหลัก', max_length=100, null=True),
        ),
    ]
