# Generated by Django 5.2 on 2025-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_curriculum_clo_edit_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
